#!/usr/bin/env zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/chomchob/google-cloud-sdk/path.zsh.inc' ]; then
  source '/Users/chomchob/google-cloud-sdk/path.zsh.inc';
fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/chomchob/google-cloud-sdk/completion.zsh.inc' ]; then
  source '/Users/chomchob/google-cloud-sdk/completion.zsh.inc';
fi
