#!/usr/bin/env zsh

# kubectl autocompletion
source <(kubectl completion zsh)

# export KUBECONFIG=~/.kube/config

# kubectl aliases
alias k='kubectl'
alias kg='kubectl get'
alias kd='kubectl describe'

alias kgp='kubectl get pod'
alias krmp='kubectl delete pod'

alias kc='kubectl config'
alias kcg='kubectl config get-contexts'
alias kcu='kubectl config use-context'
