#!/usr/bin/env zsh

# kubectl autocompletion
source <(kubectl completion zsh)

export KUBECONFIG=~/.kube/config

# kubectl aliases

alias kpproxy='kubectl --context=prod proxy --port 8001'
alias kdproxy='kubectl --context=gke_dev proxy --port 8002'

alias kc='kubectl config'
alias kcg='kubectl config get-contexts'
alias kcu='kubectl config use-context'

alias kp='kubectl --context=prod'
alias kpc='kubectl config'
alias kpcg='kubectl config get-contexts'
alias kpcu='kubectl config use-context'

# helm aliases
alias hp='helm --kube-context prod --tiller-namespace=production'

alias hd='helm --kube-context gke_dev --tiller-namespace=develop'

alias h26='helm26'
alias h26d='helm26 --kube-context gke_dev'
